CREATE TABLE job.tb_naver_aptlist_org (
	aptcd varchar(6) NULL,
	aptnm varchar(100) NULL,
	zonecd varchar(10) NULL,
	realestatecd varchar(10) NULL,
	realestatenm varchar(12) NULL,
	addressdetail varchar(100) NULL,
	latitude numeric NULL,
	longitude numeric NULL,
	hocnt numeric NULL,
	dongcnt numeric NULL,
	maxflr numeric NULL,
	minflr numeric NULL,
	approvedate varchar(8) NULL,
	dealcnt numeric NULL,
	leasecnt numeric NULL,
	rentcnt numeric NULL,
	shortrentcnt numeric NULL,
	addr varchar(100) NULL,
	pnu varchar(19) NULL,
	apt_cd varchar(10) NULL
);